### ISSUE TITLE
Update citation for group protocols

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/group-procedures#48]
**Task to do**

Archive group protocols so that it is citeable with a DOI

**Reason**

To cite our awesome group protocols.

**Result**

A citation for our group protocol

**Steps to take**

- [x] Create a CITATION.cff file (in PR)
- [ ] Decide how often to make releases
- [x] Flip the switch on Zenodo
- [ ] Make initial release on GitHub
- [ ] ~~Add DOI and other citation info to _[quarto.yml](https://quarto.org/docs/reference/projects/books.html#section)~~ Opened #53 for this

**Comment by Aariq** [comment]
When I do this, I'll also add a PR template to remind first-time contributors to add themselves to CITATION.cff

**Comment by dlebauer** [comment]
> remind first-time contributors to add themselves to CITATION.cff

consistent with the group's guidelines for defining and acknowledging contributions https://cct-datascience.github.io/group-procedures/incubator.html#defining-and-acknowledging-contributions
